environment:
  MSYS2_ARCH: i686
  MSYSTEM: MINGW32

install:
  - PATH C:\msys64\MINGW32\bin;C:\msys64\usr\bin;%PATH%
  - bash -lc "pacman --noconfirm --sync --refresh --refresh pacman"
  - bash -lc "pacman --noconfirm --sync --refresh --refresh --sysupgrade --sysupgrade"
  - bash -xlc "pacman --noconfirm -S --needed base-devel mingw-w64-i686-toolchain"
  - appveyor DownloadFile https://github.com/alainfrisch/flexdll/releases/download/0.37/flexdll-bin-0.37.zip
  - dir
  - 7z.exe e flexdll-bin-0.37.zip -o flexdll -y
  
build_script:
  - dir %APPVEYOR_BUILD_FOLDER%
